# Generated by Django 3.1.7 on 2021-05-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('whom', models.CharField(choices=[('DGP', 'DGP'), ('ADGP', 'ADGP'), ('IGP', 'IGP'), ('DIGP', 'DIGP'), ('SP', 'SP')], max_length=10, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compliant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('district', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Cognizable', 'Cognizable'), ('Non Cognizable', 'Non Cognizable'), ('Missing Report', 'Missing Case'), ('Theft Report', 'Theft Case')], max_length=50, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
            ],
        ),
        migrations.CreateModel(
            name='Noc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('need', models.CharField(choices=[('NOC for Employment', 'NOC for Employment'), ('NOC for Immigration', 'NOC for Immigration'), ('NOC for Student', 'NOC for Student')], max_length=30, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
