# Generated by Django 3.1.7 on 2021-05-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliant',
            name='email',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='compliant',
            name='mobile',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='compliant',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
