# Generated by Django 3.1.7 on 2021-05-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_auto_20210504_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliant',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='compliant',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
