# Generated by Django 3.1.7 on 2021-05-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_auto_20210504_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
