# Generated by Django 3.1.7 on 2021-05-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0007_auto_20210506_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=30)),
                ('alert', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('lanndmark', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
            ],
        ),
    ]
