# Generated by Django 3.1.7 on 2021-05-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0009_auto_20210518_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
